=== IvanKiselevichWork/XmlParsingTaskKiselevich/xml/greenhouse.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
		targetNamespace="http://www.example.com/flowers"
		xmlns:tns="http://www.example.com/flowers"
		elementFormDefault="qualified">
	<element name="flowers">
		<complexType>
			<sequence>
				<element name="flower"
						 type="tns:Flower"
						 minOccurs="2"
						 maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
	<complexType name="Flower">
		<sequence>
			<element name="name" type="string" />
			<element name="soil" type="tns:Soil" />
			<element name="origin" type="string" />
			<element name="visual_parameters" type="tns:VisualParameters" />
			<element name="growing_tips" type="tns:GrowingTips" />
			<element name="multiplying" type="tns:Multiplying" />
		</sequence>
		<attribute name="id" type="tns:Id" use="required" />
	</complexType>
	<simpleType name="Soil">
		<restriction base="string">
			<enumeration value="подзолистая"/>
			<enumeration value="грунтовая"/>
			<enumeration value="дерново-подзолистая"/>
		</restriction>
	</simpleType>
	<complexType name="VisualParameters">
		<sequence>
			<element name="body_color" type="string" />
			<element name="leaf_color" type="string" />
			<element name="general_size" type="tns:GeneralSize" />
		</sequence>
	</complexType>
	<simpleType name="GeneralSize">
		<restriction base="string">
			<enumeration value="Small"/>
			<enumeration value="Normal"/>
			<enumeration value="Big"/>
		</restriction>
	</simpleType>
	<complexType name="GrowingTips">
		<sequence>
			<element name="growing_terms" type="string" />
			<element name="temperature" type="string" />
			<element name="light" type="string" />
			<element name="watering" type="positiveInteger" />
		</sequence>
	</complexType>
	<simpleType name="Multiplying">
		<restriction base="string">
			<enumeration value="Leaf"/>
			<enumeration value="Cherenki"/>
			<enumeration value="Semen"/>
		</restriction>
	</simpleType>
		<simpleType name="Id">
		<restriction base="ID">
			<pattern value="(\\d){3,5}" />
		</restriction>
	</simpleType>
</schema>

=== IvanKiselevichWork/XmlParsingTaskKiselevich/xml/greenhouse.xml
<?xml version="1.0" encoding="UTF-8" ?>
<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema"
         xsi:schemaLocation="greenhouse.xsd">
    <flower id="1">
        <name>Rose</name>
        <soil>подзолистая</soil>
        <origin>Italy</origin>
        <visual_parameters>
            <body_color>green</body_color>
            <leaf_color>green-dark</leaf_color>
            <general_size>Small</general_size>
        </visual_parameters>
        <growing_tips>
            <growing_terms>warm and dampness</growing_terms>
            <temperature>20-25</temperature>
            <light>low</light>
            <watering>200</watering>
        </growing_tips>
        <multiplying>Stem</multiplying>
    </flower>
    <flower id="2">
        <name>Romashka</name>
        <soil>грунтовая</soil>
        <origin>Belarus</origin>
        <visual_parameters>
            <body_color>blue</body_color>
            <leaf_color>red</leaf_color>
            <general_size>Big</general_size>
        </visual_parameters>
        <growing_tips>
            <growing_terms>dry</growing_terms>
            <temperature>15-20</temperature>
            <light>medium</light>
            <watering>100</watering>
        </growing_tips>
        <multiplying>Leaf</multiplying>
    </flower>
</flowers>
